In [1]:
import numpy as np

In [2]:
def print_obj(obj, name):
    #print("%s:\n%s\n" % (name, obj))
    print(f"{name}\n{obj}\n")

# check_each(a, b) → elementwise comparison → boolean array.
def check_each(a, b):
    return (a == b).astype('bool')

# check_mean(a, b) → checks whether any element matches → single boolean.
def check_mean(a, b):
    return np.mean(a == b).astype('bool')

### Scalars, Vectors, Matrices

In [3]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a
1.0

b
[1. 2. 3.]

c
[[1. 2. 3.]
 [4. 5. 6.]]



In [5]:
print_obj(a.ndim, "a.ndim")
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")

a.ndim
0

b.ndim
1

c.ndim
2



In [6]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")

a.shape
()

b.shape
(3,)

c.shape
(2, 3)



### Tensors (N-dimensional array)

In [7]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [8]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

d
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim
3

d.shape
(2, 2, 3)

e
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim
4

e.shape
(2, 2, 2, 3)



In [9]:
# Quiz: What is the shape of [[[1], [2], [3]], [[4], [5], [6]]]?
# Ans: 2, 3, 1
# proof:
test = np.array([[[1], [2], [3]], [[4], [5], [6]]])
test.shape

(2, 3, 1)

### Defining Numpy arrays

In [10]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
a = np.zeros((2, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
a = np.full((2,5), 5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [13]:
a = np.random.random((2, 3, 4))
a

array([[[0.0671185 , 0.39412296, 0.69022459, 0.79732717],
        [0.85911306, 0.20482383, 0.81063036, 0.49597481],
        [0.82240091, 0.57335111, 0.45210169, 0.90344698]],

       [[0.91837543, 0.30606933, 0.36776961, 0.26614003],
        [0.65780339, 0.45245931, 0.33571009, 0.98407025],
        [0.70992466, 0.88291557, 0.9301362 , 0.09586386]]])

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.arange(10).astype(float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
a = np.arange(10).reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
# Quiz: Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0
a = np.arange(0, 24).reshape((4,3,2))
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

### Indexing & Slicing

In [18]:
# Indexing and slicing a vector
a = np.arange(10)
print_obj(a, "a")

print_obj(a[0], "a[0]")
print_obj(a[1], "a[1]")
print_obj(a[-1], "a[-1]")
print_obj(a[-3], "a[-3]")

print_obj(a[0:10], "a[0:10]")
print_obj(a[0:], "a[0:]")
print_obj(a[:10], "a[:10]")
print_obj(a[:], "a[:]")

print_obj(a[7:], "a[7:]")
print_obj(a[:5], "a[:5]")
print_obj(a[2:5], "a[2:5]")

# Quiz: What is a[-4:]?
# A: [6, 7, 8, 9]
# Quiz: What is a[:-8]?
# A: [2, 3, 4, 5, 6, 7, 8, 9]

print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")

print_obj(a[::-1], "a[::-1]")
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]")

# Quiz: Create [9, 6, 3] using a.
# A: a[9: 0: -3]

a
[0 1 2 3 4 5 6 7 8 9]

a[0]
0

a[1]
1

a[-1]
9

a[-3]
7

a[0:10]
[0 1 2 3 4 5 6 7 8 9]

a[0:]
[0 1 2 3 4 5 6 7 8 9]

a[:10]
[0 1 2 3 4 5 6 7 8 9]

a[:]
[0 1 2 3 4 5 6 7 8 9]

a[7:]
[7 8 9]

a[:5]
[0 1 2 3 4]

a[2:5]
[2 3 4]

a[0:10:2]
[0 2 4 6 8]

a[0:10:3]
[0 3 6 9]

a[2:6:3]
[2 5]

a[::-1]
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]
[8 7 6]

a[8:5]
[]



In [19]:
# testing my answers for the quiz
a[-4:], a[-8:], a[9: 0: -3]

(array([6, 7, 8, 9]), array([2, 3, 4, 5, 6, 7, 8, 9]), array([9, 6, 3]))

# finished till here - 20 Aug 2025

In [39]:
# Indexing a matrix
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")

# Quiz: How to access the last row?
print_obj(a[-1], "a[-1]")
# Quiz: How to access the second column?
print_obj(a[: , 1], "a[: , 1]")
# Quiz: How to create [8, 5] using a?
print_obj(a[-1:-3:-1, 2], "a[-1:-3:-1, 2]")

a
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]
0

a[0,0]
0

a[1,1]
4

a[-1]
[6 7 8]

a[: , 1]
[1 4 7]

a[-1:-3:-1, 2]
[8 5]



In [53]:
# Indexing and slicing a 3D tensor
a = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(a, "a")
print_obj(a[2, 1, 0], "a[2, 1, 0]")

# Quiz: What would be a[0]?
# A: [[0 1]
#     [2 3]]
#     [ 4 5]
print_obj(a[0], 'a[0]')
# Quiz: What would be a[0, 1]?
# [0 1]
print_obj(a[0, 1], "a[0, 1]")
# Quiz: Create [[0, 2, 4], [6, 8, 10]]
print_obj(a[:2, :, 0], "[[0, 2, 4], [6, 8, 10]]")

a
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]
14

a[0]
[[0 1]
 [2 3]
 [4 5]]

a[0, 1]
[2 3]

[[0, 2, 4], [6, 8, 10]]
[[ 0  2  4]
 [ 6  8 10]]



In [74]:
# Conditional indexing
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")

# idx = a % 2 == 0
# print_obj(idx, "idx")

idx = a >= 3

# Quiz: How would you create [3, 4, 5] using a?
print_obj(a[idx], "[3, 4, 5]")

a
[[0 1]
 [2 3]
 [4 5]]

[3, 4, 5]
[3 4 5]



In [78]:
# Taking specific elements from a vector
a = np.arange(10)
print_obj(a, 'a')
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")

a
[0 1 2 3 4 5 6 7 8 9]

a[idx]
[0 2 3]



In [81]:
# Taking specific elements from a tensor
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:,[0, 2, 3]], "a[:,[0, 2, 3]]")
print_obj(a[[0, 2, 3], :], "a[[0, 2, 3], :]")
idx = ((0,0,1,5),(1,2,0,3))
print_obj(a[idx], "tuple indexing")
idx = np.array([[0,0,1,5],[1,2,0,3]])
print_obj(a[idx], "ndarray indexing")

a
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[:,[0, 2, 3]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[[0, 2, 3], :]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

tuple indexing
[ 1  2  4 23]

ndarray indexing
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]



In [82]:
# Ellipsis
a = np.arange(288).reshape((2,3,2,2,4,-1))
print_obj(a.shape, "a.shape")

print_obj(a[1,:,:,:,:,2], "Plain indexing")
print_obj(a[1,...,2], "Ellipsis")

a.shape
(2, 3, 2, 2, 4, 3)

Plain indexing
[[[[146 149 152 155]
   [158 161 164 167]]

  [[170 173 176 179]
   [182 185 188 191]]]


 [[[194 197 200 203]
   [206 209 212 215]]

  [[218 221 224 227]
   [230 233 236 239]]]


 [[[242 245 248 251]
   [254 257 260 263]]

  [[266 269 272 275]
   [278 281 284 287]]]]

Ellipsis
[[[[146 149 152 155]
   [158 161 164 167]]

  [[170 173 176 179]
   [182 185 188 191]]]


 [[[194 197 200 203]
   [206 209 212 215]]

  [[218 221 224 227]
   [230 233 236 239]]]


 [[[242 245 248 251]
   [254 257 260 263]]

  [[266 269 272 275]
   [278 281 284 287]]]]



### Math Operations

In [ ]:
# Basic operations
a = np.arange(6).reshape((3, 2))
b = np.ones((3, 2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

In [ ]:
# Unary operations
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)")
print_obj(a.sum(axis=1), "a.sum(axis=1)")

print_obj(a.mean(), "a.mean()")
print_obj(a.max(), "a.max()")
print_obj(a.min(), "a.min()")

# Quiz: Given a = np.arange(24).reshape((2,3,4)), what is the mean of the sum w.r.t to the last dimension?

In [ ]:
# Vector dot product
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")

In [ ]:
# Matrix dot product, matrix multiplication
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")
print_obj(a@b, "a @ b")

In [ ]:
# Tensor dot product, tensor multiplication
a = np.arange(24).reshape((4, 3, 2))
b = np.ones((4, 2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b).shape, "a dot b")
print_obj((a@b).shape, "a @ b")

# Quiz: what would happen if a.shape==(4,3,2) and b.shape==(2,3)?

### Shape Manipulation

In [ ]:
# Reshapes
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1))
print_obj(c, "c")

# Quiz: What would d=a.reshape((6, 4, -1)) look like?

In [ ]:
# Adding an extra dimension
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")

# Quiz: How to make a = np.ones((3,4)) into shape (3, 1, 1, 4) using reshape and None?

In [ ]:
# Stack, concatenation
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.vstack([a, b]), "a,b vstack")
print_obj(np.hstack([a, b]), "a,b hstack")
print_obj(np.hstack([a, b, a]), "a,b hstack")

print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0")
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1")

# Quiz: Would concatenating two tensors whose shapes are (4, 3, 2) and (5, 4, 2) on axis=2 work?

In [ ]:
# Matrix transpose
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

In [ ]:
# Tensor transpose
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")

b = np.transpose(a, [0, 2, 1])
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2])
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

### Broadcasting

In [ ]:
# Vector and scalar
a = np.arange(3)
b = 2.
print_obj(a, "a")

print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

In [ ]:
# Matrix and vector
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

# Quiz: What would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1, 2))?

In [ ]:
# Tensor and matrix
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

#Quiz: How can we use None to do a+b?

### Final Quiz

In [ ]:
def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following (assume m is an even number):
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (?, 4n)
# - Linearly transform X with W so that you obtain a matrix Y of shape (?, ?)
# - Put Y through the sigmoid function
# - Obtain the sum of the mean of each column
def foo(M, W):
    return 0.